---
title: "EU State Aid Cases"
author: "Joshua C. Fjelstul, Ph.D."
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{state-aid-cases}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This article provides an overview of EU state aid cases to help users understand the ```cases``` and ```decisions``` datasets in the ```euaid``` package.

The ```cases``` dataset includes all state aid cases that the Commission has opened in response to member states notifying state aid measures, and the unit of observation is a case. The ```decisions``` dataset includes all decisions made in all state aid cases, and the unit of observation is a decision. 

## What is State Aid?

The Commission defines state aid as "an advantage in any form whatsoever conferred on a selective basis to undertakings by national public authorities." ^[https://ec.europa.eu/competition/state_aid/overview/index_en.html] State aid has four key features: there has to be an intervention in the economy by an EU member state, that intervention has to give the firm that receives the aid an advantage over other firms, the intervention has to distort competition, and the intervention has to affect intra-EU trade (trade between member states). 

[Article 107](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E107) of the Treaty on the Functioning of the European Union (TFEU) generally prohibits state aid, but allows some exemptions. [Article 108](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) allows the Commission to decide if state aid is compatible with the rules of the EU's single market.

## Treaty Articles

There are three articles of the Treaty on the Function of the European Union (TFEU) that related directly to state aid. [Article 107(1)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E107) generally prohibits state aid: 

> Save as otherwise provided in the Treaties, any aid granted by a Member State or through State resources in any form whatsoever which distorts or threatens to distort competition by favouring certain undertakings or the production of certain goods shall, in so far as it affects trade between Member States, be incompatible with the internal market.

[Article 107(2)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E107) allows state aid that has a social character, that is in response to natural disasters, or that is related to the reunification of Germany. [Article 107(3)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E107) allows state aid that promotes economic development, enables projects that are of "common European interest" or addresses a serious disturbance to a member state economy, facilitates economic activities in areas where aid does not adversely affect trade, or promotes culture and heritage conservation.

[Article 108(1)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) allows the Commission to monitor state aid granted by member states. [Article 108(2)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) creates an institutional procedure that the Commission can use to reject state aid that is not compatible with the rules of the single market, according to [Article 107](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E107). [Article 108(3)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) requires member states to notify the Commission of all state aid measures and to wait to implement measures until the Commission have approved them under the procedure created in [Article 108(2)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108). [Article 108(4)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) allows the Commission to adopt regulations relating to certain categories of state aid that, according to any Council regulations passed under [Article 109](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:12008E109), are exempt from the [Article 108(2)](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) procedure.

[Article 109](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:12008E109) allows the Council to enact regulations for the application of [Articles 107](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E107) an [Article 108](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) and to determine when member states are exempt from reporting state aid measures to the Commission under [Article 108(3)](https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX:12008E108).

## The Commission State Aid Procedure

[Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659) of 22 March 1999 defines the state aid approval procedure created by [Article 108(2) TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108). This regulation was amended by [Council Regulation (EU) No 734/2013](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32013R0734) of 22 July 2013 and then repealed and replaced by [Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589) of 13 July 2015. 

[Article 108(3) TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) requires member states to notify state aid measures to the Commission. Once a member state has notified a state aid measure, the Commission opens a state aid case and determines whether or not the measure is compatible with the rules of the single market, as defined by [Article 107 TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E107). This procedure has two phases: a preliminary examination and, if necessary, a formal investigation.

If a measure is exempt from the [Article 108(3) TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) notification requriement under [Article 108(4) TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108), which is either because the measure falls under a block exemption (see below) or because the aid is *de minimis* (below a certain amount), then the member state must still report certain information about the measure to the Commission. That information goes into the Commission's [database](https://webgate.ec.europa.eu/competition/transparency/public?lang=en) of state aid awards granted by member states.

### Phase 1: Preliminary Examination

The first phase of the procedure is the preliminary examination. If the state aid measure is not exempt from notification, the Commission will initiate a preliminary examination under [Article 4 of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 4 of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659). The Commission then has two months to evaluate the measure. The Commission can decide that the measure does not constitute state aid (paragraph 2), to not raise objections to the measure because it is compatible with the rules of the single market (paragraph 3), or to initiate a formal investigation (paragraph 4). The Commission can also decide to extend the two-month preliminary examination phase (paragraph 4). 

### Phase 2: Formal Investigation

The second phase of the procedure is the formal investigation under [Article 9 of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 7 of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659). The Commission can decide that the measure does not constitute state aid (paragraph 2), it can decide that the measure is compatible with the rules of the single market and approve the measure (a "positive decision") (paragraph 3), it can approve the measure subject to conditions that make the measure compatible with the rules of the single market (a "conditional decision") (paragrph 4), or it can decide that the measure is not compatible with the rules of the single market and not approve the measure (a "negative decision") (paragraph 5).

The Commission can remedy situations where the member state has already awarded unlawful aid. If the Commission decides that the measure is not compatible with the single market, and the member state has already awarded aid to firms, it can issue a negative decision with recovery under [Article 16(1) of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 14(1) of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659), which requires the member state to take all necessary measures to recover the aid from beneficiaries. 

If the Commission believes that a state aid measure is not compatible with the single market, it can also issue a recommendation under [Article 22 of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 18 of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659), proposing alternative measures that would be compatible with the single market.

### Withdrawal of Cases

The member state that notified the state aid measure can withdraw the notification at any time during a preliminary examination, under [Article 10(1) of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 8(1) of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659), or during a formal investigation, under [Article 10(2) of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 8(2) of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659).

### Revocation of Decisions

The Commission can also revoke any decision it has made as part of a preliminary examination or a formal investigation, under [Article 11 of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 9 of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659), if information provided by a member state that the Commission used in making the decision was incorrect. 

### Injunctions

If the Commission needs more information to make a decision, and a member state does not respond to a Commission request or provides incomplete information, the Commission can issue an information injunction to require the member state to provide the information under [Article 12(3) of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 10(3) of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659). 

In situations where a member state has already adopted a measure that the Commission suspects is not compatible with the rules of the single market, the Commission can issue a suspention injunction under [Article 13(1) of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 11(1) of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659), to require the member state to suspend the measure until the Commission can reach a decision.

### Referrals to the Court

There are a number of situations in which the Commission can refer a state aid case to the Court of Justice. The Commission can directly refer a case to the Court for non-compliance with a decision under the [Article 108(2) TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E108) procedure, as reiterated by [Article 28(1) of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 23(1) of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659), without going through the standard infringement process outlined in [Articles 258 TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E258) and [Article 260 TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E260). 

In addition, if a member state does not comply with an injunction (an information injunction or a suspension injunction), the Commission can also refer a case under [Article 14 of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 12 of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659).

If a member state does not comply with the ruling of the Court in a state aid case, [Article 28(2) of Council Regulation (EU) 2015/1589](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:32015R1589), formerly [Article 23(2) of Council Regulation (EC) No 659/1999](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:31999R0659), allows the Commission to refer the case back to the Court under the standard [Article 260 TFEU](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:12008E260) procedure. 

## Enabling Regulations

Council Regulation (EC) No 994/98 of 7 May 1998 (enabling regulation) 

* Council Regulation (EC) No 994/98 was amended by Council Regulation (EU) No 733/2013 of 22 July 2012

* Council Regulation (EC) No 994/98 was repealed and replaced by Council Regulation (EU) 2015/1588 of 13 July 2015

Commission Regulation (EU) No 1407/2013 of 18 December 2013 (de minimis aid)

* Commission Regulation (EU) No 1407/2013 was amended by Commission Regulation (EU) 2020/972 of 2 July 2020

## Block Exemptions

The Council has enacted a number of regulations that exempt certain categories of state aid from the Article 108(3) TFEU notification procedure. 

Commission Regulation (EC) No 800/2008 of 6 August 2008 identifies categories of aid that are compatible with the common market, as defined by Article 107 TFEU. 

* Commission Regulation (EC) No 800/2008 was amended by Commission Regulation (EU) No 1224/2013 of 29 November 2013

* Commission Regulation (EC) No 800/2008 was repealed and replaced by Commission Regulation (EU) No 651/2014 of 17 June 2014

* Commission Regulation (EU) No 651/2014 was amended by Commission Regulation (EU) 2017/1084 of 14 June 2017

* Commission Regulation (EU) No 651/2014 was amended by Commission Regulation (EU) 2020/972 of 2 July 2020

## Transparency Requirements

In addition to updating the GBER, Commission Regulation (EU) No 651/2014 of 17 June 2014 creates new transparency requirements that are part of the Commission's State Aid Modernisation (SAM) programe.


