################################################################################
# Joshua C. Fjelstul, Ph.D.
# eusa R package
# automatically generated by the codebookr R package
################################################################################

#' CSTS data on cases (by member state and aid instrument)
#' 
#' This dataset includes aggregated data on the number of state aid awards per
#' member state per year (cross-sectional time-series data) broken down by aid
#' instrument. There is one observation per member state per year per aid
#' instrument (2016-2020).
#' 
#' @format A data frame with 9 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{Numeric. The year the case was opened by the Commission.}
#' \item{member_state_id}{Numeric. An ID number that uniquely identifies each
#' member state. This ID number is assigned when member states are sorted by
#' accession date and then alphabetically. }
#' \item{member_state}{String. The name of the member state that the
#' Commission opened the case against. }
#' \item{member_state_code}{String. A two letter code assigned by the
#' Commission that uniquely identifies each member state. }
#' \item{aid_instrument_id}{Numeric. An ID number that uniquely identifies
#' each state aid instrument that a granting authority can use.}
#' \item{aid_instrument}{String. The aid instrument that the granting
#' authority used in granting the state aid award.}
#' \item{count_awards}{Numeric. A count of the number of state aid awards
#' granted by the member state at this level of aggregation.}
#' \item{total_amount_awards}{Numeric. The total amount of awards granted at
#' this level of aggregation in euros.}
#' }
"awards_csts_ai"

################################################################################
# end R script
################################################################################

