################################################################################
# Joshua C. Fjelstul, Ph.D.
# eusa R package
# automatically generated by the codebookr R package
################################################################################

#' TS data on cases
#' 
#' This dataset includes aggregated data on the number of state aid cases per
#' year (time-series data). There is one observation per year (1988-2020).
#' 
#' @format A data frame with 3 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{Numeric. The year the case was opened by the Commission.}
#' \item{count_cases}{Numeric. A count of the number of cases opened by the
#' Commission at this level of aggregation.}
#' }
"cases_ts"

################################################################################
# end R script
################################################################################

