################################################################################
# Joshua C. Fjelstul, Ph.D.
# eusa R package
# automatically generated by the codebookr R package
################################################################################

#' Decision-level time-series data
#' 
#' This dataset includes aggregated data on the number of each type of
#' decision per year (time-series data). There is one observation per year per
#' decision stage (1988-2020).
#' 
#' @format A data frame with 5 variables:
#' \describe{
#' \item{key_id}{\code{numeric}. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{\code{numeric}. The year the case was opened by the
#' Commission.}
#' \item{decision_type_id}{\code{numeric}. An ID number that uniquely
#' identifies each type of decision the Commission can make in a state aid
#' case.}
#' \item{decision_type}{\code{string}. The type of the decision.}
#' \item{count_decisions}{\code{numeric}. A count of the number of decisions
#' issued by the Commission at this level of aggregation.}
#' }
"decisions_ts"

################################################################################
# end R script
################################################################################

