################################################################################
# Joshua C. Fjelstul, Ph.D.
# eusa R package
# automatically generated by the codebookr R package
################################################################################

#' Network data on decisions
#' 
#' This dataset includes multi-dimensional network data for decisions in state
#' aid cases. There is one dimension per decision type. Network data is
#' similar to directed dyad-year data except that it only includes directed
#' dyad-years with at least one decision. For every year, there is one node
#' per department and one node per member state. Edges can only exist between
#' a department and a member state. There is an edge between a department and
#' a member state with respect to each decision type if and only if the
#' department issued at least one decision against the member state during
#' that year. The weight of the edge is the number of decisions that the
#' department opened against the member state. There is one observation per
#' department per member state per year per decision type (1988-2020),
#' excluding directed dyad-years where the state was not a member of the EU,
#' but only if count of decisions is positive.
#' 
#' @format A data frame with 11 variables:
#' \describe{
#' \item{key_id}{Numeric. An ID number that uniquely identifies each
#' observation in the dataset. }
#' \item{year}{Numeric. The year the case was opened by the Commission.}
#' \item{department_id}{Numeric. An ID number that uniquely identifies each
#' Directorate-General (DG) of the Commission. There are three DGs that can
#' open state aid cases. The DG for Competition (COMP) is coded \code{1}, the
#' DG for Agriculture and Rural Development (AGRI) is coded \code{2}, and the
#' DG for Maritime Affairs and Fisheries (MARE) is coded \code{3}.}
#' \item{department}{String. The name of the Directorate-General (DG) of the
#' Commission that opened the state aid case.}
#' \item{department_code}{String. A multi-letter code assigned by the
#' Commission that uniquely identifies each Directorate-General (DG) of the
#' Commission. }
#' \item{member_state_id}{Numeric. An ID number that uniquely identifies each
#' member state. This ID number is assigned when member states are sorted by
#' accession date and then alphabetically. }
#' \item{member_state}{String. The name of the member state that the
#' Commission opened the case against. }
#' \item{member_state_code}{String. A two letter code assigned by the
#' Commission that uniquely identifies each member state. }
#' \item{decision_type_id}{Numeric. An ID number that uniquely identifies each
#' type of decision the Commission can make in a state aid case.}
#' \item{decision_type}{String. The type of the decision.}
#' \item{count_decisions}{Numeric. A count of the number of decisions issued
#' by the Commission at this level of aggregation.}
#' }
"decisions_net"

################################################################################
# end R script
################################################################################

